# Generated by Django 5.2 on 2025-04-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concern',
            name='text',
        ),
        migrations.AddField(
            model_name='concern',
            name='ai_suggestion',
            field=models.TextField(default='未入力'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concern',
            name='concern_text',
            field=models.TextField(default='未入力'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concern',
            name='scene_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
